services:
- type: web
  name: monorepo-test-service
  branch: main
  env: node
  buildCommand: cd service && ./build.sh
  startCommand: cd service && ./start.sh
- type: web
  name: monorepo-test-service-docker
  branch: main
  env: docker
  dockerfilePath: ./service-docker/Dockerfile
  dockerContext: .
  dockerCommand: bash ./service-docker/start.sh
  healthCheckPath: /health-check
- type: web
  name: monorepo-test-static-site
  branch: main
  env: static
  buildCommand: cd static-site && ./build.sh
  staticPublishPath: ./static-site/
- type: cron
  name: monorepo-test-cron-job
  env: go
  startCommand: echo "Hello World 👋"
  schedule: "0 5 * * *"
- type: cron
  name: monorepo-test-cron-job-docker
  env: docker
  dockerfilePath: ./cron-job-docker/Dockerfile
  dockerContext: .
  dockerCommand: bash ./cron-job-docker/start.sh
  schedule: "0 5 * * *"
